Add files via upload
Running into issues calling the file to open. 
Output from terminal:
michaelsullivan@Michaels-MacBook-Air ~ % /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Users/michaelsullivan/repo/Election-Analysis/Pypoll.py
Traceback (most recent call last):
  File "/Users/michaelsullivan/repo/Election-Analysis/Pypoll.py", line 19, in <module>
    with open(file) as election_data:
FileNotFoundError: [Errno 2] No such file or directory: 'resources/election_result.csv'

Adding resources folder to git hub.
This repository was cloned and changes (including file structure) have not been merged. Maybe that's the issue?